# CI file for GCC builds

name: Build GCC libgultra

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build repo
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [L] # [H, I, I_patch, J, K, L]
        suffix: [~, _d, _rom]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install package requirements
      run: sudo apt-get install -y clang-tools-19 clang-format-19 clang-tidy-19 gcc-mips-linux-gnu binutils-mips-linux-gnu build-essential python3

    - name: Verify formatting on all files
      run: python3 tools/check_format.py --verbose

    - name: Setup
      run: make setup -j $(nproc) TARGET=libgultra${{ matrix.suffix }} VERSION=${{ matrix.version }}

    - name: Build libgultra${{ matrix.suffix }} ${{ matrix.version }}
      run: make -j $(nproc) TARGET=libgultra${{ matrix.suffix }} VERSION=${{ matrix.version }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: 'Changes to Apply'
        path: changes.patch
        retention-days: 5
